public inherited sharing class casecreationhandler {
    @AuraEnabled
    public static string createcasemethod(case caseRec, string file, string fileName) {
        string caseId;
        try{  
            Insert caseRec; 
            caseId = caseRec.Id;  
            String base64File = EncodingUtil.urlDecode(file, 'UTF-8');     
            ContentVersion contentVersionRec = new ContentVersion();  
            contentVersionRec.Title = fileName;  
            contentVersionRec.PathOnClient = '/' + fileName;  
            contentVersionRec.FirstPublishLocationId = caseRec.Id;  
            contentVersionRec.VersionData = EncodingUtil.base64Decode(base64File);  
            contentVersionRec.IsMajorVersion = true;  
            Insert contentVersionRec;  
          } catch(Exception ex){  
            system.debug('Exception===>'+ex.getMessage());  
          }  
          return caseId;  
    }
}
